### ISSUE TITLE
Code not called after building

### ISSUE THREAD

**Issue by khibma** [Esri/esri-wab-build#52]
This might not be a legit issue, but I can't prove it is/is not.

Inside **jimu.js\configloader.js** I was overriding config files if the locale was different. Basically updating the path to a different file. After building, this area of code would never be hit.
```
      function loadWidgetManifest(widgetManager, e, portalUrl){
        function _doLoadWidgetManifest(e){
          if (dojoConfig.locale.indexOf("fr") >= 0){
            if (e.name === "Geoprocessing"){
              e.config = "configs/Geoprocessing/config__29FR.json";
              console.log("Geoprocessing:FR");
            }
          } 
```

I was able to overcome this by moving the logic out of configloader and into **jimu.js\WidgetManager.js**. Anywhere near the start of _loadWidgetManifest_ with the same logic as above works. I'm ok with this. Like I said, not sure if its a legit issue that after building it skipped an area of code (setting break points within the above code of configloader is always glossed over.

**Comment by rsjones** [comment]
@khibma Thanks for letting us know.  While we're not intending to support this type of customization with this tool, I'm glad you found a location for your code that works.
