### ISSUE TITLE
Build fails with error no such file or directory

### ISSUE THREAD

**Issue by petemahoney** [Esri/esri-wab-build#54]
I've run this build against two projects and I'm getting the same fail error for both.  One is a complex WAB app with a bunch of widgets and the other is a very plain basic app that has almost nothing in it.

[NpmErrorOutput.txt](https://github.com/gbochenek/esri-wab-build/files/2429934/NpmErrorOutput.txt)

I've attached the output of the npm error I get - obviously just the tail end of it as the cmd line output is very verbose I couldn't copy it all - well I guess I could if I piped it to a file - let me know if that will help.

This is my first attempt at using your tool - head about it from a friend who was at the dev summit this year.  So maybe I'm doing something wrong - but I did follow the instructions.

Any ideas??

Thanks!

**Comment by petemahoney** [comment]
Update - I probably should have mentioned this before but when running that build back in September, I was running against apps created with v2.4 of WAB DE.  Today I thought I'd see if it would work with v2.9 and it did.  So question is, how can I get it to work against v2.4?  We are tied to that version because we are trying to stay in sync with our ArcGIS Enterprise Portal which is at 10.5.1, which I understand/assume to be 'in sync', code, api or otherwise, with DE 2.4.  Might be good to verify that assumption as well if anybody knows.

**Comment by dpmarley** [comment]
Hi,

I work with petemahoney and am just adding a little more information here. The first errors that appear in the console output from the build are:
```
error(311) Missing dependency. module: moment/min/tests; dependency: ../../moment 
error(311) Missing dependency. module: moment/min/tests; dependency: ../../moment
error(311) Missing dependency. module: moment/min/tests; dependency: ../../moment 
```
There are several other `Missing dependency` entries, as well as these `Missing include module for layer` errors:

```
error(303) Missing include module for layer. missing: jimu/DataSourceManager; layer: jimu/main
error(303) Missing include module for layer. missing: jimu/dijit/GridLayout; layer: jimu/dijit-all
```

As petemahoney noted, we are using WAB Developer Edition 2.4.  Test builds with a version 2.9 WAB application work fine.

The full console log/output is attached:
[ConEmu-2019-03-06-p4672.log](https://github.com/gbochenek/esri-wab-build/files/2939635/ConEmu-2019-03-06-p4672.log)

**Comment by matlegdal** [comment]
I got that same issue with very simple demo apps with only one widget. Both WAB 2.9 and 2.11 fail the same way.

I tried to use `bower cache clean` like indicated in the readme, but it didn't solve the issue.

**Comment by rsjones** [comment]
@petemahoney unfortunately we aren't supporting versions back all the way to 2.4. Changes in WAB and the jsapi make this difficult over time. You could try to use an older version of the tool, but the trade off would be the loss of functionality like vector tile layers (we hadn't figured those out in early versions of the build). I always am a proponent of good custom vs WAB code so that you can easily upgrade to the latest version of the WAB.
